name: platzi_trips_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # BLoC Arq
  generic_bloc_provider: ^1.0.9
  # Firebase
  firebase_core: ^0.4.0+3
  firebase_auth:
  google_sign_in:
  cloud_firestore: ^0.12.5
  firebase_storage: ^3.0.1
  #Camara
  image_picker: ^0.6.0+9
  #Performance - Cache
  cached_network_image: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/people.jpg
    - assets/img/ann.jpg
    - assets/img/girl.jpg
    - assets/img/mountain.jpeg
    - assets/img/beach.jpeg
    - assets/img/beach_palm.jpeg
    - assets/img/mountain_stars.jpeg
    - assets/img/sunset.jpeg
    - assets/img/river.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf